### ISSUE TITLE
Integrate macvlan and bridge cni driver

### ISSUE THREAD

**Issue by paolovisintin** [Huawei-PaaS/CNI-Genie#49] opened 2017-09-20 07:32 UTC
actually only Calico, Flannel, Romana, Weave are supported

**Comment by xiaods** [comment] 2017-10-10 08:41
interesting it, any process here?

**Comment by kshafiee** [comment] 2017-10-12 17:31
@xiaods we started working on this Issue, we will update you shortly

**Comment by fnurglewitz** [comment] 2017-10-31 07:07
@kshafiee any news about this issue?

**Comment by xiaods** [comment] 2017-10-31 08:16
indeed...

**Comment by kshafiee** [comment] 2017-10-31 16:09
@sushanthakumar could you please provide updates so everyone interested is aware of the progress? Thx!

**Comment by xiaods** [comment] 2017-11-01 06:25
my wechat:  coderxiao

**Comment by satyaranjanp** [comment] 2017-11-02 05:17
We have completed the implementation and started testing it. Should be able to raise PR in 2-3 days

**Comment by xiaods** [comment] 2017-11-02 05:42
@satyaranjanp cool!!!

**Comment by paolovisintin** [comment] 2017-11-02 21:49
really awesome! 
I look forward to test !!!!

**Comment by sushanthakumar** [comment] 2017-11-09 16:55
For bridge support, below PR is raised
https://github.com/Huawei-PaaS/CNI-Genie/pull/54

Macvlan support to follow soon

**Comment by paolovisintin** [comment] 2017-11-16 18:12
Hi @sushanthakumar , 
do you have any update about macvlan deployment ?  
Many thanks!

**Comment by sushanthakumar** [comment] 2017-11-17 06:29
@paolovisintin , yes it is developed and tested, should be merged in 1-2 days

**Comment by paolovisintin** [comment] 2017-11-22 08:10
Hi @sushanthakumar , thanks for the update, will test as soon as it will be merged in master!
Thanks

**Comment by kshafiee** [comment] 2017-11-22 20:20
@paolovisintin please feel free to fetch PR #59 to use 'macvlan' and provide feedback.
We are right now looking into whether 'DefaultIpamForMacvlan' should be "dhcp" or "host-local" before we merge into master

**Comment by fnurglewitz** [comment] 2017-11-27 10:56
@kshafiee I'm having some problems while testing the macvlan support: I was trying to setup a simple pod with a macvlan interface (a busybox+sleep pod to keep it the simplest possible), there are no problems with weave but when i try to use macvlan the pods keeps staying in "ContainerCreating" status, on the syslog i found [some errors](https://pastebin.com/K6d1ZH7i) related to the [macvlan configuration](https://pastebin.com/5VTdVj4k).

It says that the "master" key is missing, but I configured it properly (tried to restart both kubelet and the whole system)

**Comment by fnurglewitz** [comment] 2017-12-05 07:35
@kshafiee did you have any time to check the logs I posted?

thanks

**Comment by kshafiee** [comment] 2017-12-05 08:28
@fnurglewitz sorry I didn't update on this earlier.
@satyaranjanp investigate and fixed this issue last week.
please get the latest code from the master branch and see if the issue is resolved

**Comment by xiaods** [comment] 2017-12-06 21:30
cool

**Comment by sushanthakumar** [comment] 2018-01-10 04:55
Below 2 merged PRs will provide support for bridge and mac vlan
https://github.com/Huawei-PaaS/CNI-Genie/pull/54
https://github.com/Huawei-PaaS/CNI-Genie/pull/59
Closing this issue

**Closed by sushanthakumar** 2018-01-10 04:55 UTC
