### ISSUE TITLE
invalid memory address or nil pointer dereference when IPAM does not return desired result

### ISSUE THREAD

**Issue by ramukima** [Huawei-PaaS/CNI-Genie#129] opened 2018-08-16 21:21 UTC
When DHCP ipam implementation could not acquire a lease, the following is shown as a result -

Aug 16 21:18:15 localhost kubelet[19237]: CNI Genie addNetwork err *** error calling DHCP.Allocate: no more tries result***  <nil>
Aug 16 21:18:15 localhost kubelet[19237]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 16 21:18:15 localhost kubelet[19237]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7c3cb7]
Aug 16 21:18:15 localhost kubelet[19237]: goroutine 1 [running, locked to thread]:
Aug 16 21:18:15 localhost kubelet[19237]: github.com/Huawei-PaaS/CNI-Genie/vendor/github.com/containernetworking/cni/pkg/types/current.NewResultFromResult(0x0, 0x0, 0x3, 0xc42001e1e0, 0xc420028070)
Aug 16 21:18:15 localhost kubelet[19237]: #011/home/salmon/code/src/github.com/Huawei-PaaS/CNI-Genie/vendor/github.com/containernetworking/cni/pkg/types/current/types.go:124 +0x37
Aug 16 21:18:15 localhost kubelet[19237]: github.com/Huawei-PaaS/CNI-Genie/genie.updateRoutes(0x0, 0x0, 0xc42001e1e0, 0x59, 0x60, 0x59)
Aug 16 21:18:15 localhost kubelet[19237]: #011/home/salmon/code/src/github.com/Huawei-PaaS/CNI-Genie/genie/genie-controller.go:796 +0x4d
Aug 16 21:18:15 localhost kubelet[19237]: github.com/Huawei-PaaS/CNI-Genie/genie.mergeWithResult(0x0, 0x0, 0x0, 0x0, 0xc42028b448, 0x2, 0x2, 0x59)
Aug 16 21:18:15 localhost kubelet[19237]: #011/home/salmon/code/src/github.com/Huawei-PaaS/CNI-Genie/genie/genie-controller.go:742 +0x50
Aug 16 21:18:15 localhost kubelet[19237]: github.com/Huawei-PaaS/CNI-Genie/genie.AddPodNetwork(0xc420014010, 0x40, 0xc42001600a, 0x11, 0xc42001201b, 0x4, 0xc420018009, 0x9d, 0xc42001a009, 0x1b, ...)
Aug 16 21:18:15 localhost kubelet[19237]: #011/home/salmon/code/src/github.com/Huawei-PaaS/CNI-Genie/genie/genie-controller.go:134 +0x77b
Aug 16 21:18:15 localhost kubelet[19237]: main.cmdAdd(0xc420256540, 0xc4200c6e98, 0x5)
Aug 16 21:18:15 localhost kubelet[19237]: #011/home/salmon/code/src/github.com/Huawei-PaaS/CNI-Genie/cni-genie.go:42 +0x485
Aug 16 21:18:15 localhost kubelet[19237]: github.com/Huawei-PaaS/CNI-Genie/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc4202589c0, 0xc420256540, 0x16c5f00, 0xc4200c3da0, 0x109cc20, 0x0, 0x410c88)
Aug 16 21:18:15 localhost kubelet[19237]: #011/home/salmon/code/src/github.com/Huawei-PaaS/CNI-Genie/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:162 +0x19f
Aug 16 21:18:15 localhost kubelet[19237]: github.com/Huawei-PaaS/CNI-Genie/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc4202589c0, 0x109cc20, 0x109cc28, 0x16c5f00, 0xc4200c3da0, 0xf3d700)
Aug 16 21:18:15 localhost kubelet[19237]: #011/home/salmon/code/src/github.com/Huawei-PaaS/CNI-Genie/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:173 +0x2a2
Aug 16 21:18:15 localhost kubelet[19237]: github.com/Huawei-PaaS/CNI-Genie/vendor/github.com/containernetworking/cni/pkg/skel.PluginMainWithError(0x109cc20, 0x109cc28, 0x16c5f00, 0xc4200c3da0, 0x4046a4)
Aug 16 21:18:15 localhost kubelet[19237]: #011/home/salmon/code/src/github.com/Huawei-PaaS/CNI-Genie/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:210 +0xed
Aug 16 21:18:15 localhost kubelet[19237]: github.com/Huawei-PaaS/CNI-Genie/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0x109cc20, 0x109cc28, 0x16c5f00, 0xc4200c3da0)
Aug 16 21:18:15 localhost kubelet[19237]: #011/home/salmon/code/src/github.com/Huawei-PaaS/CNI-Genie/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:222 +0x4d

**Comment by bsshetty** [comment] 2018-08-18 10:44
@ramukima, We will look into ur scenario and update u, thanks

**Comment by satyaranjanp** [comment] 2018-08-20 06:28
@ramukima 
There was a known panic issue in case of nil result from cni, which has already been fixed and merged to master branch. Below is the PR details:
https://github.com/Huawei-PaaS/CNI-Genie/pull/110
I observed the same panic issue without the above fix and the issue is not happening with the latest code.
Please verify your scenario with the latest code and let us know if it is working fine.

**Closed** 2018-10-10 05:42 UTC
